Repository shorian/GreatOutdoors, pull requests merged in 2025-02, with the labels that each got.

#44 Established basic grid layout and container elements
  index.html
  styles/styles.css
Labels: Sprint Backlog

#77 Created custom element for banner. Minor style cleanup.
  falls.html
  ferry.html
  forest.html
  index.html
  lake.html
  mountain.html
  park.html
  scripts/components/banner.js
  styles/styles.css
  template.html
Labels: enhancement, Product Backlog, Sprint Backlog

#80 Added name to README
  README.md
Labels: P3

#81 Created assignment workflow
  .github/workflows/close-unlabeled-issues.yml
Labels: P0
